version: "3"
services:
  app:
    image: eclipse-mosquitto
#    network_mode: host
    volumes:
      - "mosquitto:/mosquitto/"
    ports:
      - "1883:1883"
      - "9001:9001"

volumes:
     mosquitto:
