version: '3'
services:
  app:
   image: nextcloud/all-in-one:latest-arm64
   ports:
      - 90:80
      - 9090:8080
      - 9443:8443
   volumes:
      - app:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
   app:
