version: '3'
services:
    app:
        image: henrywhitaker3/speedtest-tracker:latest-arm
        ports:
            - 83:80
        volumes:
            - speedtest:/config
        environment:
            - TZ=Europe/Berlin
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"

volumes:
     speedtest:
